#!/usr/bin/env python3
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]

def replace_once(path, old, new):
    p=ROOT/path
    text=p.read_text(encoding='utf-8')
    n=text.count(old)
    if n!=1: raise RuntimeError(f'{path}: expected one occurrence, found {n}: {old[:100]!r}')
    p.write_text(text.replace(old,new,1),encoding='utf-8')

# Add incumbent pass-through to browser contract without changing strict mode.
replace_once('site/preflop-contract.js',
"""  const normalizeActionProbabilities=({context,raw_probabilities,hand_class=null,sizing=null,source,backoff_level,confidence,support})=>{\n    const legal=(context.legal_actions||[]).map(x=>String(x).toUpperCase());if(!legal.length)throw new Error('context has no legal actions');const weights={};let total=0;for(const action of legal){const v=Number((raw_probabilities||{})[action]||0);if(!Number.isFinite(v)||v<0)throw new Error(`invalid probability weight for ${action}`);weights[action]=v;total+=v;}if(total<=EPS)throw new Error('zero legal probability mass');const probabilities={};for(const action of legal)probabilities[action]=weights[action]/total;return {schema:PROBABILITY_SCHEMA,context_id:String(context.context_id||contextId(context)),hand_class,legal_actions:legal,probabilities,sizing:sizing==null?null:{...sizing},source:String(source),backoff_level:String(backoff_level),confidence:String(confidence),support:Number(support)||0,incumbent_compatibility:{matcher:'v5/v83',runtime_signature_ignores_free_check:true}};\n  };\n  return {SCHEMA,PROBABILITY_SCHEMA,STATE_TIMING,normalizePosition:normPos,sortPositions,normalizeHistory,historyToken,deriveRemainingToAct,familyFromHistory,legalActionsForState,canonicalKey,contextId,buildContext,v5RuntimeSignature,normalizeActionProbabilities};\n""",
"""  const normalizeActionProbabilities=({context,raw_probabilities,hand_class=null,sizing=null,source,backoff_level,confidence,support})=>{\n    const legal=(context.legal_actions||[]).map(x=>String(x).toUpperCase());if(!legal.length)throw new Error('context has no legal actions');const weights={};let total=0;for(const action of legal){const v=Number((raw_probabilities||{})[action]||0);if(!Number.isFinite(v)||v<0)throw new Error(`invalid probability weight for ${action}`);weights[action]=v;total+=v;}if(total<=EPS)throw new Error('zero legal probability mass');const probabilities={};for(const action of legal)probabilities[action]=weights[action]/total;return {schema:PROBABILITY_SCHEMA,behavior_mode:'strict_legal_normalized',context_id:String(context.context_id||contextId(context)),hand_class,legal_actions:legal,probabilities,sizing:sizing==null?null:{...sizing},source:String(source),backoff_level:String(backoff_level),confidence:String(confidence),support:Number(support)||0,incumbent_compatibility:{matcher:'v5/v83',runtime_signature_ignores_free_check:true}};\n  };\n  const incumbentV5Passthrough=({context,raw_probabilities,hand_class=null,sizing=null,source,backoff_level,confidence,support})=>{\n    const probabilities={},raw=raw_probabilities||{};let total=0;for(const [action,valueRaw] of Object.entries(raw)){const actionName=String(action).toUpperCase(),value=Number(valueRaw||0);if(!Number.isFinite(value)||value<0)throw new Error(`invalid incumbent probability for ${actionName}`);probabilities[actionName]=value;total+=value;}if(!Object.keys(probabilities).length)throw new Error('incumbent probability response is empty');if(total<=EPS)throw new Error('incumbent probability mass is zero');const legal=(context.legal_actions||[]).map(x=>String(x).toUpperCase()),legalSet=new Set(legal),positiveIllegal=Object.entries(probabilities).filter(([,p])=>p>EPS).map(([a])=>a).filter(a=>legal.length&&!legalSet.has(a)),missing=legal.filter(a=>!Object.prototype.hasOwnProperty.call(probabilities,a));return {schema:PROBABILITY_SCHEMA,behavior_mode:'incumbent_v5_passthrough',context_id:String(context.context_id||contextId(context)),hand_class,legal_actions:legal,model_actions:Object.keys(probabilities),probabilities,probability_sum:total,action_set_compatible:positiveIllegal.length===0,positive_illegal_model_actions:positiveIllegal,missing_legal_model_actions:missing,sizing:sizing==null?null:{...sizing},source:String(source),backoff_level:String(backoff_level),confidence:String(confidence),support:Number(support)||0,incumbent_compatibility:{matcher:'v5/v83',probabilities_preserved_without_renormalization:true,runtime_signature_ignores_free_check:true}};\n  };\n  return {SCHEMA,PROBABILITY_SCHEMA,STATE_TIMING,normalizePosition:normPos,sortPositions,normalizeHistory,historyToken,deriveRemainingToAct,familyFromHistory,legalActionsForState,canonicalKey,contextId,buildContext,v5RuntimeSignature,normalizeActionProbabilities,incumbentV5Passthrough};\n""")

# Runtime consumes the wrapper, but the multiplied probability is identical.
replace_once('site/index.html',
"""    for(const h of hands){\n      weights[h]=(weights[h]||0)*Math.max(0,Number(policy[h]?.[decision.action])||0);\n    }\n""",
"""    let actionSetCompatible=true;\n    for(const h of hands){\n      const probabilityResponse=window.PokerPreflopContract.incumbentV5Passthrough({\n        context:decision.preflop_context_v1||decision,raw_probabilities:policy[h]||{},hand_class:h,\n        source:policy.__source||'legacy_reconstructed',backoff_level:match.exact?'exact':'closest',\n        confidence:match.node.population_model?.confidence||'',support:Number(match.node.coverage?.population_decisions)||0\n      });\n      actionSetCompatible=actionSetCompatible&&probabilityResponse.action_set_compatible;\n      weights[h]=(weights[h]||0)*Math.max(0,Number(probabilityResponse.probabilities[decision.action])||0);\n    }\n""")
replace_once('site/index.html',
"""      policyMethod:policy.__method||\"\",\n      family:match.node.context?.family||\"\",\n""",
"""      policyMethod:policy.__method||\"\",\n      probabilityContract:'poker-preflop-action-probabilities/v1',\n      probabilityMode:'incumbent_v5_passthrough',\n      actionSetCompatible,\n      backoffLevel:match.exact?'exact':'closest',\n      family:match.node.context?.family||\"\",\n""")

# Temporary machinery must not survive.
for rel in ('tools/tmp_issue96_probability.py','.github/workflows/issue96-probability.yml'):
    p=ROOT/rel
    if p.exists():p.unlink()
print('probability runtime compatibility patch applied')
