#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
from pathlib import Path
from typing import Any

SCHEMA = "poker-project-capabilities/v1"
REPORT_SCHEMA = "poker-project-state-report/v1"
STATES = [
    "CONTRACT_READY",
    "SCIENTIFICALLY_SELECTED",
    "PRODUCT_INTEGRATED",
    "PROMOTED",
    "LIVE",
]
STATE_RANK = {state: rank for rank, state in enumerate(STATES)}
GENERATED_MARKER = "<!-- generated by tools/validate_project_state.py --render-status -->"


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        value = json.load(handle)
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected a JSON object")
    return value


def _json_pointer(document: Any, pointer: str) -> Any:
    if pointer == "":
        return document
    if not isinstance(pointer, str) or not pointer.startswith("/"):
        raise ValueError(f"invalid JSON pointer: {pointer!r}")
    current = document
    for raw in pointer.split("/")[1:]:
        token = raw.replace("~1", "/").replace("~0", "~")
        if isinstance(current, list):
            try:
                current = current[int(token)]
            except (ValueError, IndexError) as exc:
                raise KeyError(pointer) from exc
        elif isinstance(current, dict):
            if token not in current:
                raise KeyError(pointer)
            current = current[token]
        else:
            raise KeyError(pointer)
    return current


def _safe_path(root: Path, relative: str) -> Path:
    path = (root / relative).resolve()
    root = root.resolve()
    try:
        path.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"path escapes repository root: {relative}") from exc
    return path


def evaluate_check(root: Path, check: dict[str, Any]) -> dict[str, Any]:
    kind = check.get("kind")
    relative = check.get("path")
    if not isinstance(relative, str) or not relative:
        return {"status": "FAIL", "message": "check path must be a non-empty string"}
    try:
        path = _safe_path(root, relative)
    except ValueError as exc:
        return {"status": "FAIL", "message": str(exc)}

    if kind == "path_exists":
        expected_type = check.get("type", "any")
        if not path.exists():
            return {"status": "FAIL", "message": f"missing path: {relative}"}
        if expected_type == "file" and not path.is_file():
            return {"status": "FAIL", "message": f"expected file: {relative}"}
        if expected_type == "dir" and not path.is_dir():
            return {"status": "FAIL", "message": f"expected directory: {relative}"}
        if expected_type not in {"any", "file", "dir"}:
            return {"status": "FAIL", "message": f"unsupported path type: {expected_type}"}
        return {"status": "PASS", "message": f"path exists: {relative}"}

    if kind == "file_contains":
        if not path.is_file():
            return {"status": "FAIL", "message": f"missing file: {relative}"}
        needle = check.get("text")
        if not isinstance(needle, str) or not needle:
            return {"status": "FAIL", "message": "file_contains requires non-empty text"}
        content = path.read_text(encoding="utf-8")
        if needle not in content:
            return {"status": "FAIL", "message": f"{relative} does not contain required text"}
        return {"status": "PASS", "message": f"{relative} contains required text"}

    if kind == "json_equals":
        if not path.is_file():
            return {"status": "FAIL", "message": f"missing JSON file: {relative}"}
        pointer = check.get("pointer")
        if not isinstance(pointer, str):
            return {"status": "FAIL", "message": "json_equals requires pointer"}
        try:
            actual = _json_pointer(load_json(path), pointer)
        except (ValueError, KeyError, json.JSONDecodeError) as exc:
            return {"status": "FAIL", "message": f"{relative}{pointer}: {exc}"}
        expected = check.get("equals")
        if actual != expected:
            return {
                "status": "FAIL",
                "message": f"{relative}{pointer}: expected {expected!r}, got {actual!r}",
            }
        return {"status": "PASS", "message": f"{relative}{pointer} == {expected!r}"}

    return {"status": "FAIL", "message": f"unsupported check kind: {kind!r}"}


def validate_manifest(manifest: dict[str, Any], root: Path) -> dict[str, Any]:
    errors: list[str] = []
    warnings: list[str] = []
    rows: list[dict[str, Any]] = []

    if manifest.get("schema") != SCHEMA:
        errors.append(f"schema must be {SCHEMA!r}")
    if manifest.get("state_order") != STATES:
        errors.append("state_order must exactly match the canonical delivery-state order")

    capabilities = manifest.get("capabilities")
    if not isinstance(capabilities, list) or not capabilities:
        errors.append("capabilities must be a non-empty list")
        capabilities = []

    seen: set[str] = set()
    for raw in capabilities:
        if not isinstance(raw, dict):
            errors.append("each capability must be an object")
            continue

        capability_id = raw.get("id")
        state = raw.get("state")
        summary = raw.get("summary")
        row = {
            "id": capability_id,
            "summary": summary if isinstance(summary, str) else "",
            "state": state,
            "evidence": [],
            "limits": [],
            "administrative_gap": None,
        }

        if not isinstance(capability_id, str) or not capability_id:
            errors.append("capability id must be a non-empty string")
            rows.append(row)
            continue
        if capability_id in seen:
            errors.append(f"{capability_id}: duplicate capability id")
        seen.add(capability_id)

        if state not in STATE_RANK:
            errors.append(f"{capability_id}: invalid state {state!r}")
            rows.append(row)
            continue

        evidence = raw.get("evidence")
        if not isinstance(evidence, list) or not evidence:
            errors.append(f"{capability_id}: at least one evidence check is required")
            evidence = []

        proves_current = False
        for index, item in enumerate(evidence):
            if not isinstance(item, dict):
                errors.append(f"{capability_id}: evidence #{index + 1} must be an object")
                continue
            proves = item.get("proves")
            if proves not in STATE_RANK:
                errors.append(f"{capability_id}: evidence #{index + 1} has invalid proves state")
                continue
            if STATE_RANK[proves] > STATE_RANK[state]:
                errors.append(f"{capability_id}: evidence claims {proves} above declared state {state}")
                continue
            result = evaluate_check(root, item)
            result.update({"id": item.get("id"), "proves": proves})
            row["evidence"].append(result)
            if result["status"] != "PASS":
                errors.append(f"{capability_id}: {result['message']}")
            if proves == state and result["status"] == "PASS":
                proves_current = True

        if not proves_current:
            errors.append(f"{capability_id}: no passing evidence proves current state {state}")

        limits = raw.get("limits", [])
        if not isinstance(limits, list):
            errors.append(f"{capability_id}: limits must be a list")
            limits = []
        for index, item in enumerate(limits):
            if not isinstance(item, dict):
                errors.append(f"{capability_id}: limit #{index + 1} must be an object")
                continue
            blocks_state = item.get("blocks_state")
            if blocks_state not in STATE_RANK:
                errors.append(f"{capability_id}: limit #{index + 1} has invalid blocks_state")
                continue
            if STATE_RANK[blocks_state] <= STATE_RANK[state]:
                errors.append(f"{capability_id}: limit {blocks_state} must be above current state {state}")
                continue
            check = item.get("check")
            if not isinstance(check, dict):
                errors.append(f"{capability_id}: limit #{index + 1} requires a check object")
                continue
            result = evaluate_check(root, check)
            result.update({"id": item.get("id"), "blocks_state": blocks_state})
            row["limits"].append(result)
            if result["status"] != "PASS":
                errors.append(f"{capability_id}: stale/invalid limit: {result['message']}")

        administrative = raw.get("administrative")
        if administrative is not None:
            if not isinstance(administrative, dict):
                errors.append(f"{capability_id}: administrative must be an object")
            else:
                claimed_state = administrative.get("claimed_state")
                status = administrative.get("status")
                if claimed_state not in STATE_RANK:
                    errors.append(f"{capability_id}: invalid administrative claimed_state")
                elif status not in {"OPEN", "CLOSED"}:
                    errors.append(f"{capability_id}: administrative status must be OPEN or CLOSED")
                elif STATE_RANK[claimed_state] > STATE_RANK[state]:
                    issue = administrative.get("issue")
                    message = (
                        f"{capability_id}: issue #{issue} is {status} with claimed "
                        f"{claimed_state}, while versioned evidence declares {state}"
                    )
                    successor = administrative.get("successor_issue")
                    reason = administrative.get("known_mismatch_reason")
                    row["administrative_gap"] = {
                        "issue": issue,
                        "status": status,
                        "claimed_state": claimed_state,
                        "successor_issue": successor,
                        "known_mismatch_reason": reason,
                    }
                    if successor and isinstance(reason, str) and reason.strip():
                        warnings.append(
                            f"{message}; tracked by successor issue #{successor}: {reason.strip()}"
                        )
                    else:
                        errors.append(f"{message}; contradiction is not traceably acknowledged")

        rows.append(row)

    status = "FAIL" if errors else ("WARN" if warnings else "PASS")
    return {
        "schema": REPORT_SCHEMA,
        "manifest_schema": manifest.get("schema"),
        "status": status,
        "errors": errors,
        "warnings": warnings,
        "capabilities": rows,
    }


def _md(value: Any) -> str:
    return str(value).replace("\\", "\\\\").replace("`", "\\`").replace("|", "\\|").replace("\n", " ")


def render_status(manifest: dict[str, Any], report: dict[str, Any]) -> str:
    counts = {state: 0 for state in STATES}
    for row in report.get("capabilities", []):
        state = row.get("state")
        if state in counts:
            counts[state] += 1

    lines = [
        "# Project Status",
        "",
        GENERATED_MARKER,
        "",
        "> AUTO-GENERATED from `.project/capabilities.json` and versioned repository evidence.",
        "> Do not edit manually. Regenerate with `python3 tools/validate_project_state.py --write-status`.",
        "",
        "## Validation",
        "",
        f"- Result: `{_md(report.get('status'))}`",
        f"- Errors: `{len(report.get('errors', []))}`",
        f"- Warnings: `{len(report.get('warnings', []))}`",
        "",
        "## Delivery-state summary",
        "",
        "| State | Capabilities |",
        "| --- | ---: |",
    ]
    lines.extend(f"| `{state}` | {counts[state]} |" for state in STATES)

    lines.extend(["", "## Capabilities", ""])
    for row in report.get("capabilities", []):
        capability_id = _md(row.get("id"))
        state = _md(row.get("state"))
        lines.append(f"### `{capability_id}` — `{state}`")
        lines.append("")
        summary = row.get("summary") or "No summary."
        lines.append(_md(summary))
        lines.extend(["", "Evidence:"])
        evidence = row.get("evidence", [])
        if evidence:
            for item in evidence:
                lines.append(
                    f"- `{_md(item.get('status'))}` `{_md(item.get('id'))}` proves "
                    f"`{_md(item.get('proves'))}` — {_md(item.get('message'))}"
                )
        else:
            lines.append("- None.")

        lines.extend(["", "Higher-state limits:"])
        limits = row.get("limits", [])
        if limits:
            for item in limits:
                marker = "ACTIVE" if item.get("status") == "PASS" else "INVALID"
                lines.append(
                    f"- `{marker}` `{_md(item.get('id'))}` blocks `{_md(item.get('blocks_state'))}` "
                    f"— {_md(item.get('message'))}"
                )
        else:
            lines.append("- None.")

        gap = row.get("administrative_gap")
        lines.extend(["", "Administrative contradiction:"])
        if gap:
            successor = gap.get("successor_issue")
            suffix = f"; successor #{successor}" if successor else ""
            reason = gap.get("known_mismatch_reason")
            if reason:
                suffix += f"; {_md(reason).rstrip('.')}"
            lines.append(
                f"- Issue #{_md(gap.get('issue'))} is `{_md(gap.get('status'))}` and claimed "
                f"`{_md(gap.get('claimed_state'))}`{suffix}."
            )
        else:
            lines.append("- None.")
        lines.append("")

    lines.extend(["## Historical contradictions", ""])
    warnings = report.get("warnings", [])
    if warnings:
        lines.extend(f"- WARN — {_md(item)}" for item in warnings)
    else:
        lines.append("- None.")

    errors = report.get("errors", [])
    lines.extend(["", "## Validation errors", ""])
    if errors:
        lines.extend(f"- ERROR — {_md(item)}" for item in errors)
    else:
        lines.append("- None.")

    lines.extend([
        "",
        "## Interpretation",
        "",
        "- A closed issue is not evidence that a capability is active, promoted, or live.",
        "- `PASS` on a higher-state limit means the blocking condition is currently evidenced.",
        "- `LIVE` requires explicit canonical-production proof; publication/build metadata alone is insufficient.",
        "",
    ])
    return "\n".join(lines)


def compare_status_file(path: Path, expected: str) -> tuple[bool, str]:
    if not path.is_file():
        return False, f"missing status file: {path}"
    actual = path.read_text(encoding="utf-8")
    if actual == expected:
        return True, ""
    diff = "".join(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=str(path),
            tofile="generated-status",
        )
    )
    return False, diff or "status content differs"


def exit_code(report: dict[str, Any], strict_warnings: bool = False) -> int:
    if report.get("status") == "FAIL":
        return 1
    if strict_warnings and report.get("status") == "WARN":
        return 2
    return 0


def _status_path(root: Path, requested: Path | None) -> Path:
    if requested is None:
        return (root / ".project" / "STATUS.md").resolve()
    if requested.is_absolute():
        path = requested.resolve()
        try:
            path.relative_to(root.resolve())
        except ValueError as exc:
            raise ValueError(f"status path escapes repository root: {requested}") from exc
        return path
    return _safe_path(root, str(requested))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate machine-readable project capability state against versioned evidence."
    )
    parser.add_argument("--manifest", type=Path, default=None)
    parser.add_argument("--root", type=Path, default=None)
    parser.add_argument("--strict-warnings", action="store_true")
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--render-status", action="store_true")
    modes.add_argument("--check-status", action="store_true")
    modes.add_argument("--write-status", action="store_true")
    parser.add_argument("--status-path", type=Path, default=None)
    args = parser.parse_args(argv)

    root = (args.root or Path(__file__).resolve().parents[1]).resolve()
    manifest_path = (args.manifest or root / ".project" / "capabilities.json").resolve()
    try:
        manifest = load_json(manifest_path)
        report = validate_manifest(manifest, root)
        rendered = render_status(manifest, report)
        status_path = _status_path(root, args.status_path)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        report = {
            "schema": REPORT_SCHEMA,
            "status": "FAIL",
            "errors": [str(exc)],
            "warnings": [],
            "capabilities": [],
        }
        print(json.dumps(report, indent=2, sort_keys=True, ensure_ascii=False))
        return 1

    if args.render_status:
        print(rendered, end="")
        return exit_code(report, strict_warnings=args.strict_warnings)

    if args.check_status:
        current, detail = compare_status_file(status_path, rendered)
        if not current:
            print(f"STATUS_STALE: {status_path}")
            if detail:
                print(detail, end="" if detail.endswith("\n") else "\n")
            return 1
        print(f"STATUS_OK: {status_path}")
        return exit_code(report, strict_warnings=args.strict_warnings)

    if args.write_status:
        if report.get("status") == "FAIL":
            print(json.dumps(report, indent=2, sort_keys=True, ensure_ascii=False))
            return 1
        status_path.parent.mkdir(parents=True, exist_ok=True)
        status_path.write_text(rendered, encoding="utf-8")
        print(f"STATUS_WRITTEN: {status_path}")
        return exit_code(report, strict_warnings=args.strict_warnings)

    print(json.dumps(report, indent=2, sort_keys=True, ensure_ascii=False))
    return exit_code(report, strict_warnings=args.strict_warnings)


if __name__ == "__main__":
    raise SystemExit(main())
