#!/usr/bin/env python3
"""#421 guard: frozen OOD / uncertainty gate and its TRAIN-only calibration.

Covers every acceptance criterion of the task:

* the statuses are stable and documented: ``MODEL_SUPPORTED``,
  ``MODEL_SUPPORTED_HIGH_UNCERTAINTY`` and ``MODEL_OOD_ABSTAIN``;
* a never-observed category abstains;
* a sizing / stack extrapolation outside the calibrated TRAIN domain abstains;
* an exact context that was never observed while every single-feature label is
  in-domain is *not* OOD by definition: it may only be high-uncertainty;
* the thresholds are calibrated on TRAIN / cross-validation only;
  ``validation_consumed`` and ``test_consumed`` are false and the calibration
  refuses to consume any other split.

``jsonschema`` is not a declared dependency of this repository, so the contract
is validated with an explicit, reviewable keyword subset, mirroring the
convention of ``tests/preflop/test_generalized_response_model.py``.  The full
TRAIN calibration is regenerated by
``python3 tools/preflop/generalized_response_model.py --ood-calibration-report``;
the guard suite reuses the persisted calibration when it exists and otherwise
calibrates a deterministic stride sample so it stays fast.
"""
from __future__ import annotations

import ast
import contextlib
import io
import json
import re
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.preflop import generalized_response_model as model  # noqa: E402

MODULE_PATH = ROOT / "tools/preflop/generalized_response_model.py"
CONTRACT_PATH = ROOT / "contracts/training/generalized-response-ood-gate.schema.json"
REPORT_PATH = ROOT / "analysis/issue421_generalized_response/OOD_CALIBRATION_REPORT.json"
DATASET_PATH = ROOT / "analysis/issue421_generalized_response/dataset/GENERALIZED_RESPONSE_DATASET.jsonl"

STATUS_SUPPORTED = model.STATUS_MODEL_SUPPORTED
STATUS_HIGH = model.STATUS_MODEL_SUPPORTED_HIGH_UNCERTAINTY
STATUS_ABSTAIN = model.STATUS_MODEL_OOD_ABSTAIN

#: Fast, deterministic calibration used only when the persisted report is absent.
FAST_FOLDS = 3
FAST_MAX_ROWS = 6000
FAST_TUNING_ROWS = 600
FAST_ARCHITECTURES = (model.ARCH_REGULARIZED,)

_CACHE: dict[str, object] = {}


def _dataset_rows(splits: tuple[str, ...] = ("TRAIN",)) -> list[dict]:
    key = "rows:" + ",".join(splits)
    if key not in _CACHE:
        _CACHE[key] = model.read_dataset_rows(DATASET_PATH, splits=splits)
    return _CACHE[key]  # type: ignore[return-value]


def _report() -> dict:
    """The persisted calibration report when present, else a fast TRAIN-only one."""
    if "report" not in _CACHE:
        if REPORT_PATH.exists():
            _CACHE["report"] = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
            _CACHE["report_source"] = "persisted_report"
        else:
            _CACHE["report"] = model.build_ood_calibration_report(
                _dataset_rows()[::16],
                folds=FAST_FOLDS,
                max_rows=FAST_MAX_ROWS,
                tuning_max_rows=FAST_TUNING_ROWS,
                architectures=FAST_ARCHITECTURES,
            )
            _CACHE["report_source"] = "fast_stride_calibration"
    return _CACHE["report"]  # type: ignore[return-value]


def _calibration() -> dict:
    return _report()["calibration"]


def _candidate() -> dict:
    if "candidate" not in _CACHE:
        # The same deterministic synthetic fixture the sibling model guard uses,
        # so the fitted candidate satisfies the persisted contract.
        rows = model.synthetic_rows(900, 421)
        candidate = model.fit(
            rows, 421, config=model.make_config(tuning_max_rows=250, holdout_modulus=5)
        )
        assert model.validate_candidate(candidate) == [], model.validate_candidate(candidate)
        _CACHE["candidate"] = candidate
    return _CACHE["candidate"]  # type: ignore[return-value]


def _train_sample() -> list[dict]:
    return _dataset_rows()[::16]


def _context(**overrides) -> dict:
    """A real TRAIN context, optionally perturbed."""
    context = dict(_train_sample()[0])
    context.update(overrides)
    return context


def _novel_in_domain_context() -> dict:
    """In-domain by label, never observed as an exact cell."""
    rows = _train_sample()
    calibration = _calibration()
    known = {block: set(counts) for block, counts in calibration["category_counts"].items()}
    support = calibration["exact_context_support"]
    for left in rows[:256]:
        for right in rows[:: max(1, len(rows) // 256)]:
            candidate = dict(left)
            for field in model.OOD_PRICE_AXES:
                candidate[field] = right.get(field)
            candidate["target_total_bb"] = None
            candidate["observed_sizing_bb"] = None
            levels = model.ood_feature_levels(candidate)
            if not all(levels[block] in known[block] for block in model.OOD_FEATURE_BLOCKS):
                continue
            if support.get(model.ood_exact_context_key(candidate), 0) == 0:
                return candidate
    raise AssertionError("no novel in-domain context found in the TRAIN sample")


# ---------------------------------------------------------------------------
# minimal, reviewable JSON-Schema subset validator
# ---------------------------------------------------------------------------


def _resolve(schema: dict, root: dict) -> dict:
    while isinstance(schema, dict) and "$ref" in schema:
        node: object = root
        for part in str(schema["$ref"]).lstrip("#/").split("/"):
            node = node[part]  # type: ignore[index]
        schema = node  # type: ignore[assignment]
    return schema


def _type_ok(value: object, expected: str) -> bool:
    if expected == "object":
        return isinstance(value, dict)
    if expected == "array":
        return isinstance(value, list)
    if expected == "string":
        return isinstance(value, str)
    if expected == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if expected == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if expected == "boolean":
        return isinstance(value, bool)
    if expected == "null":
        return value is None
    raise AssertionError(f"unsupported schema type in the reviewable subset: {expected!r}")


def _errors(value: object, schema: dict, root: dict, path: str) -> list[str]:
    schema = _resolve(schema, root)
    if not isinstance(schema, dict):
        return [f"{path}: schema node is not an object"]
    errors: list[str] = []
    if "const" in schema and value != schema["const"]:
        errors.append(f"{path}: expected const {schema['const']!r}, got {value!r}")
    if "enum" in schema and value not in schema["enum"]:
        errors.append(f"{path}: {value!r} is outside {schema['enum']!r}")
    if "oneOf" in schema:
        matches = sum(1 for branch in schema["oneOf"] if not _errors(value, branch, root, path))
        if matches != 1:
            errors.append(f"{path}: matched {matches} oneOf branches")
    expected = schema.get("type")
    if expected is not None and not _type_ok(value, expected):
        errors.append(f"{path}: expected {expected}, got {type(value).__name__}")
        return errors
    if isinstance(value, dict):
        for key in schema.get("required", []):
            if key not in value:
                errors.append(f"{path}: missing required property {key!r}")
        properties = schema.get("properties") or {}
        if schema.get("additionalProperties") is False:
            extra = sorted(set(value) - set(properties))
            if extra:
                errors.append(f"{path}: unexpected properties {extra}")
        for key, sub in properties.items():
            if key in value:
                errors.extend(_errors(value[key], sub, root, f"{path}.{key}"))
    if isinstance(value, list):
        if "minItems" in schema and len(value) < schema["minItems"]:
            errors.append(f"{path}: fewer than {schema['minItems']} items")
        if "maxItems" in schema and len(value) > schema["maxItems"]:
            errors.append(f"{path}: more than {schema['maxItems']} items")
        if "items" in schema:
            for index, item in enumerate(value):
                errors.extend(_errors(item, schema["items"], root, f"{path}[{index}]"))
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        if "minimum" in schema and value < schema["minimum"]:
            errors.append(f"{path}: {value} < minimum {schema['minimum']}")
        if "maximum" in schema and value > schema["maximum"]:
            errors.append(f"{path}: {value} > maximum {schema['maximum']}")
    if isinstance(value, str) and "pattern" in schema:
        if not re.match(schema["pattern"], value):
            errors.append(f"{path}: {value!r} does not match {schema['pattern']!r}")
    return errors


def validate_against_contract(value: object, contract: dict) -> None:
    errors = _errors(value, contract, contract, "$")
    if errors:
        raise AssertionError("contract violation:\n" + "\n".join(errors))


# ---------------------------------------------------------------------------
# status / contract surface
# ---------------------------------------------------------------------------


class StatusContractTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.calibration = _calibration()
        cls.candidate = _candidate()
        cls.contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))

    def test_statuses_are_stable_and_documented(self) -> None:
        self.assertEqual(
            model.OOD_STATUSES,
            ("MODEL_SUPPORTED", "MODEL_SUPPORTED_HIGH_UNCERTAINTY", "MODEL_OOD_ABSTAIN"),
        )
        self.assertEqual(list(model.OOD_STATUS_DEFINITIONS), list(model.OOD_STATUSES))
        for status in model.OOD_STATUSES:
            self.assertTrue(model.OOD_STATUS_DEFINITIONS[status].strip())
        self.assertEqual(model.OOD_GATE_SCHEMA, "poker-generalized-response-ood-gate/v1")
        self.assertEqual(
            model.OOD_CALIBRATION_SCHEMA, "poker-generalized-response-ood-calibration/v1"
        )
        self.assertEqual(
            model.OOD_REPORT_SCHEMA, "poker-generalized-response-ood-calibration-report/v1"
        )
        self.assertTrue(set(model.OOD_HARD_REASONS) <= set(model.OOD_REASON_ORDER))
        self.assertTrue(set(model.OOD_SOFT_REASONS) <= set(model.OOD_REASON_ORDER))
        self.assertFalse(set(model.OOD_HARD_REASONS) & set(model.OOD_SOFT_REASONS))
        self.assertEqual(STATUS_SUPPORTED, "MODEL_SUPPORTED")
        self.assertEqual(STATUS_HIGH, "MODEL_SUPPORTED_HIGH_UNCERTAINTY")
        self.assertEqual(STATUS_ABSTAIN, "MODEL_OOD_ABSTAIN")

    def test_contract_pins_the_gate_surface(self) -> None:
        contract = self.contract
        self.assertEqual(contract["$schema"], "https://json-schema.org/draft/2020-12/schema")
        self.assertEqual(len(contract["oneOf"]), 3)
        self.assertEqual(
            list(contract["$defs"]["status"]["enum"]), list(model.OOD_STATUSES)
        )
        self.assertEqual(
            contract["$defs"]["oodGateDecision"]["properties"]["schema"]["const"],
            model.OOD_GATE_SCHEMA,
        )
        self.assertEqual(
            contract["$defs"]["calibration"]["properties"]["schema"]["const"],
            model.OOD_CALIBRATION_SCHEMA,
        )
        self.assertEqual(
            contract["$defs"]["oodCalibrationReport"]["properties"]["schema"]["const"],
            model.OOD_REPORT_SCHEMA,
        )
        self.assertIs(
            contract["$defs"]["calibration"]["properties"]["exact_context_diagnostic_only"]["const"],
            True,
        )
        self.assertEqual(
            sorted(contract["$defs"]["reasonCode"]["enum"]), sorted(model.OOD_REASON_ORDER)
        )
        self.assertEqual(
            sorted(contract["$defs"]["thresholds"]["required"]),
            sorted(
                [
                    "min_feature_share",
                    "min_exact_context_share",
                    "min_model_node_support_per_row",
                    "normalized_entropy",
                    "domain_distance",
                    "extrapolation_margin",
                ]
            ),
        )

    def test_decision_calibration_and_report_validate_against_the_contract(self) -> None:
        decision = model.ood_gate_decision(
            self.candidate, _context(), calibration=self.calibration
        )
        validate_against_contract(decision, self.contract)
        validate_against_contract(self.calibration, self.contract)
        validate_against_contract(_report(), self.contract)

    def test_module_structural_validators_accept_their_own_output(self) -> None:
        self.assertEqual(model.validate_ood_calibration(self.calibration), [])
        decision = model.ood_gate_decision(self.candidate, _context(), calibration=self.calibration)
        self.assertEqual(model.validate_ood_decision(decision), [])
        tampered = dict(decision)
        tampered["abstain"] = not bool(decision["abstain"])
        self.assertTrue(model.validate_ood_decision(tampered))
        tampered = json.loads(json.dumps(self.calibration))
        tampered["provenance"]["validation_consumed"] = True
        self.assertTrue(model.validate_ood_calibration(tampered))

    def test_module_imports_only_the_standard_library(self) -> None:
        tree = ast.parse(MODULE_PATH.read_text(encoding="utf-8"))
        allowed = {
            "argparse",
            "bisect",
            "hashlib",
            "json",
            "math",
            "sys",
            "pathlib",
            "typing",
            "__future__",
        }
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    self.assertIn(alias.name.split(".")[0], allowed, alias.name)
            elif isinstance(node, ast.ImportFrom) and node.module:
                self.assertIn(node.module.split(".")[0], allowed, node.module)


# ---------------------------------------------------------------------------
# gate behaviour
# ---------------------------------------------------------------------------


class GateBehaviourTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.calibration = _calibration()
        cls.candidate = _candidate()
        cls.domain = cls.calibration["domain"]

    def _decide(self, context: dict, model_: object = None) -> dict:
        return model.ood_gate_decision(
            self.candidate if model_ is None else model_, context, calibration=self.calibration
        )

    def test_decision_carries_the_machine_readable_status(self) -> None:
        decision = self._decide(_context())
        self.assertEqual(decision["schema"], model.OOD_GATE_SCHEMA)
        self.assertIn(decision["status"], model.OOD_STATUSES)
        self.assertEqual(decision["abstain"], decision["status"] == STATUS_ABSTAIN)
        self.assertEqual(decision["supported"], not decision["abstain"])
        self.assertEqual(decision["high_uncertainty"], decision["status"] == STATUS_HIGH)
        self.assertFalse(decision["validation_consumed"])
        self.assertFalse(decision["test_consumed"])
        self.assertEqual(
            decision["calibration"]["canonical_payload_sha256"],
            self.calibration["canonical_payload_sha256"],
        )
        for key in model.OOD_NUMERIC_AXES:
            self.assertIn(key, decision["signals"]["axes"])
        self.assertIs(decision["signals"]["exact_context"]["decisive"], False)
        self.assertEqual(model.validate_ood_decision(decision), [])

    def test_never_seen_category_abstains(self) -> None:
        for overrides, expected in (
            ({"family": "NEVER_OBSERVED_FAMILY_421"}, "UNSEEN_CATEGORY"),
            ({"actor_position": "ZZ"}, "UNSEEN_CATEGORY"),
            ({"aggressor_position": "YY"}, "UNSEEN_CATEGORY"),
            ({"to_call_bb": 7777.0}, "EXTRAPOLATION_PRICE"),
        ):
            with self.subTest(overrides=overrides):
                decision = self._decide(_context(**overrides))
                self.assertEqual(decision["status"], STATUS_ABSTAIN)
                self.assertTrue(decision["abstain"])
                self.assertIn(expected, decision["reasons"], decision["reasons"])

    def test_capped_count_features_are_absorbed_by_the_model_resolution(self) -> None:
        # The model caps the count features, so an out-of-range count is *not* a
        # never-seen category: it maps onto the shared capped node.
        for overrides in (
            {"raise_level": 99},
            {"limper_count": 99},
            {"caller_count": 99},
            {"live_positions": ["LJ", "HJ", "CO", "BTN", "SB", "BB"], "table_size": 9},
        ):
            with self.subTest(overrides=overrides):
                decision = self._decide(_context(**overrides))
                self.assertEqual(decision["signals"]["unseen_categories"], {})
                self.assertNotEqual(decision["status"], STATUS_ABSTAIN)

    def test_sizing_extrapolation_abstains(self) -> None:
        ratio_high = float(self.domain[model.OOD_SIZING_AXIS]["trained_max"])
        row = dict(_context())
        row["target_total_bb"] = None
        denominator = float(row["pot_before_bb"]) + float(row["to_call_bb"])
        query = dict(row, target_total_bb=(ratio_high * 2.0 + 10.0) * denominator)
        decision = self._decide(query)
        self.assertEqual(decision["status"], STATUS_ABSTAIN)
        self.assertIn("EXTRAPOLATION_SIZING", decision["reasons"])
        self.assertTrue(decision["signals"]["axes"][model.OOD_SIZING_AXIS]["extrapolation"])

    def test_stack_extrapolation_abstains(self) -> None:
        high = float(self.domain["effective_stack_bb"]["trained_max"])
        low = float(self.domain["effective_stack_bb"]["trained_min"])
        for stack in (high * 2.0 + 10.0, max(low * 0.5, 0.0)):
            with self.subTest(stack=stack):
                decision = self._decide(_context(effective_stack_bb=stack))
                self.assertEqual(decision["status"], STATUS_ABSTAIN)
                self.assertIn("EXTRAPOLATION_STACK", decision["reasons"])

    def test_spline_boundary_inside_domain_is_high_uncertainty_not_abstain(self) -> None:
        knot_max = float(max(model.make_config()["spline_knots"]["effective_stack_bb"]))
        trained_max = float(self.domain["effective_stack_bb"]["trained_max"])
        if trained_max <= knot_max:
            self.skipTest("the calibrated stack domain has no in-domain spline-boundary region")
        decision = self._decide(_context(effective_stack_bb=trained_max))
        self.assertEqual(decision["signals"]["unseen_categories"], {})
        self.assertTrue(decision["signals"]["axes"]["effective_stack_bb"]["spline_boundary"])
        self.assertFalse(decision["signals"]["axes"]["effective_stack_bb"]["extrapolation"])
        self.assertEqual(decision["status"], STATUS_HIGH)

    def test_exact_context_absent_in_domain_is_not_ood(self) -> None:
        novel = _novel_in_domain_context()
        support = self.calibration["exact_context_support"]
        self.assertEqual(support.get(model.ood_exact_context_key(novel), 0), 0)
        decision = self._decide(novel)
        self.assertEqual(decision["signals"]["unseen_categories"], {})
        self.assertEqual(decision["signals"]["exact_context"]["support"], 0)
        self.assertFalse(decision["signals"]["exact_context"]["seen_in_calibration"])
        self.assertIs(decision["signals"]["exact_context"]["decisive"], False)
        self.assertNotEqual(decision["status"], STATUS_ABSTAIN)
        self.assertFalse(decision["abstain"])
        self.assertIn(decision["status"], (STATUS_SUPPORTED, STATUS_HIGH))
        self.assertNotIn(STATUS_ABSTAIN, decision["hard_reasons"])
        # The contrast: the very same context with a never-seen category abstains.
        contrast = self._decide(dict(novel, family="NEVER_OBSERVED_FAMILY_421"))
        self.assertEqual(contrast["status"], STATUS_ABSTAIN)

    def test_exact_context_absence_alone_never_abstains(self) -> None:
        # The exact-context signal is declared non-decisive: a never-observed
        # exact cell can never, on its own, flip the status to ABSTAIN.
        novel = _novel_in_domain_context()
        decision = self._decide(novel)
        hard = set(decision["hard_reasons"])
        self.assertNotIn("LOW_EXACT_CONTEXT_SUPPORT", hard)
        self.assertFalse(any(reason.startswith("EXTRAPOLATION") for reason in hard))
        self.assertNotEqual(decision["status"], STATUS_ABSTAIN)

    def test_gate_without_a_model_never_claims_support(self) -> None:
        decision = model.ood_gate_decision(None, _context(), calibration=self.calibration)
        self.assertIn("PREDICTIVE_UNCERTAINTY_UNAVAILABLE", decision["reasons"])
        self.assertNotEqual(decision["status"], STATUS_SUPPORTED)
        self.assertIsNone(decision["signals"]["predictive_uncertainty"])
        self.assertEqual(model.validate_ood_decision(decision), [])

    def test_response_model_wrapper_exposes_the_gate(self) -> None:
        wrapper = model.ResponseModel(self.candidate)
        decision = wrapper.ood_gate(_context(), calibration=self.calibration)
        self.assertEqual(decision["status"], wrapper.ood_status(_context(), calibration=self.calibration))
        self.assertIn(decision["status"], model.OOD_STATUSES)

    def test_decision_is_deterministic(self) -> None:
        first = self._decide(_context())
        second = self._decide(_context())
        self.assertEqual(first, second)

    def test_missing_domain_axis_fails_closed(self) -> None:
        sparse = {key: value for key, value in _context().items() if key != "pot_before_bb"}
        decision = self._decide(sparse)
        self.assertEqual(decision["status"], STATUS_ABSTAIN)
        self.assertIn("MISSING_DOMAIN_AXIS", decision["reasons"])

    def test_out_of_domain_context_returns_a_decision_instead_of_raising(self) -> None:
        decision = self._decide(
            {
                "family": "TOTALLY_UNKNOWN",
                "actor_position": "ZZ",
                "aggressor_position": "YY",
                "limper_count": 9,
                "caller_count": 9,
                "live_positions": ["BTN"],
                "table_size": 6,
                "raise_level": 42,
                "to_call_bb": 10_000.0,
                "pot_before_bb": 20_000.0,
                "effective_stack_bb": 50_000.0,
            }
        )
        self.assertEqual(decision["status"], STATUS_ABSTAIN)
        self.assertEqual(model.validate_ood_decision(decision), [])

    def test_default_loader_reads_the_persisted_report(self) -> None:
        if not REPORT_PATH.exists():
            self.skipTest("the OOD calibration report has not been generated in this worktree")
        loaded = model.load_ood_calibration()
        decision = model.ood_gate_decision(self.candidate, _context(), calibration=loaded)
        self.assertEqual(model.validate_ood_decision(decision), [])
        self.assertIn(decision["status"], model.OOD_STATUSES)


# ---------------------------------------------------------------------------
# calibration protocol
# ---------------------------------------------------------------------------


class CalibrationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.calibration = _calibration()
        cls.report = _report()
        cls.sample = _train_sample()

    def test_calibration_is_train_only(self) -> None:
        provenance = self.calibration["provenance"]
        self.assertEqual(provenance["consumed_splits"], ["TRAIN"])
        self.assertFalse(provenance["validation_consumed"])
        self.assertFalse(provenance["test_consumed"])
        self.assertEqual(
            provenance["threshold_calibration"],
            "train_only_hand_grouped_cross_validation",
        )
        self.assertEqual(
            sorted(self.calibration["thresholds"]),
            sorted(
                [
                    "min_feature_share",
                    "min_exact_context_share",
                    "min_model_node_support_per_row",
                    "normalized_entropy",
                    "domain_distance",
                    "extrapolation_margin",
                    "support_floor_share",
                ]
            ),
        )
        self.assertGreater(self.calibration["thresholds"]["min_exact_context_share"], 0.0)
        self.assertGreater(self.calibration["thresholds"]["min_feature_share"], 0.0)
        self.assertGreaterEqual(self.calibration["thresholds"]["normalized_entropy"], 0.0)
        self.assertLessEqual(self.calibration["thresholds"]["normalized_entropy"], 1.0)
        self.assertEqual(
            sorted(self.calibration["category_counts"]), sorted(model.OOD_FEATURE_BLOCKS)
        )
        self.assertIs(self.calibration["exact_context_diagnostic_only"], True)

    def test_calibration_refuses_validation_and_test_rows(self) -> None:
        validation = model.read_dataset_rows(DATASET_PATH, splits=("VALIDATION",))[:8]
        with self.assertRaises(model.GeneralizedResponseModelError):
            model.build_ood_calibration_report(
                self.sample + validation,
                folds=2,
                max_rows=400,
                tuning_max_rows=200,
                architectures=FAST_ARCHITECTURES,
            )
        test = [dict(row, split="TEST") for row in self.sample[:4]]
        with self.assertRaises(model.GeneralizedResponseModelError):
            model.build_ood_calibration_report(
                test, folds=2, max_rows=4, tuning_max_rows=2, architectures=FAST_ARCHITECTURES
            )

    def test_calibration_is_order_independent_and_deterministic(self) -> None:
        first = model.build_ood_calibration_report(
            self.sample,
            folds=2,
            max_rows=800,
            tuning_max_rows=200,
            architectures=FAST_ARCHITECTURES,
        )
        second = model.build_ood_calibration_report(
            list(reversed(self.sample)),
            folds=2,
            max_rows=800,
            tuning_max_rows=200,
            architectures=FAST_ARCHITECTURES,
        )
        self.assertEqual(
            first["calibration"]["canonical_payload_sha256"],
            second["calibration"]["canonical_payload_sha256"],
        )
        self.assertEqual(first["calibration"], second["calibration"])

    def test_thresholds_come_from_out_of_fold_train_evidence(self) -> None:
        report = self.report
        evidence = report["calibration_evidence"]
        protocol = evidence["protocol"]
        self.assertEqual(protocol["kind"], "train_only_hand_grouped_cross_validation")
        self.assertEqual(protocol["consumed_splits"], ["TRAIN"])
        self.assertFalse(protocol["validation_consumed"])
        self.assertFalse(protocol["test_consumed"])
        self.assertGreaterEqual(protocol["folds"], 2)
        self.assertGreater(evidence["records"], 0)
        self.assertTrue(evidence["folds"])
        self.assertTrue(all(set(record) >= {"fold", "fit_rows", "holdout_rows"} for record in evidence["folds"]))
        for key, quantiles in evidence["signal_quantiles"].items():
            self.assertGreater(quantiles["n"], 0, key)
            self.assertLessEqual(quantiles["min"], quantiles["median"], key)
            self.assertLessEqual(quantiles["median"], quantiles["p95"], key)
        thresholds = report["calibration"]["thresholds"]
        self.assertGreaterEqual(
            thresholds["min_exact_context_share"],
            thresholds["support_floor_share"] - 1e-18,
        )
        self.assertGreaterEqual(
            thresholds["min_feature_share"], thresholds["support_floor_share"] - 1e-18
        )

    def test_out_of_fold_evidence_never_abstains_on_absent_in_domain_contexts(self) -> None:
        report = self.report
        oof = report["out_of_fold"]
        self.assertEqual(sum(oof["counts"].values()), oof["n"])
        self.assertEqual(sorted(oof["by_stratum"]), sorted(model.OOD_STRATA))
        absent = oof["exact_context_absent_in_domain"]
        self.assertEqual(absent["abstained_without_extrapolation"], 0)
        self.assertEqual(
            sum(absent["statuses"].values()),
            absent["rows"],
        )
        self.assertGreater(absent["rows"], 0)
        self.assertTrue(all(share is None or 0.0 <= share <= 1.0 for share in oof["shares"].values()))

    def test_report_acceptance_checks_pass(self) -> None:
        report = self.report
        checks = report["acceptance_checks"]
        for key, value in checks.items():
            self.assertTrue(value, key)
        rules = report["gate_rules"]
        self.assertTrue(rules["never_seen_category_abstains"])
        self.assertTrue(rules["sizing_extrapolation_abstains"])
        self.assertTrue(rules["stack_extrapolation_abstains"])
        self.assertEqual(rules["thresholds_calibrated_on"], ["TRAIN", "CV"])
        self.assertFalse(rules["validation_consumed"])
        self.assertFalse(rules["test_consumed"])
        self.assertIn("exact", rules["exact_context_absent_is_not_ood"])
        self.assertEqual(report["scope"]["consumed_splits"], ["TRAIN"])
        self.assertFalse(report["scope"]["validation_consumed"])
        self.assertFalse(report["scope"]["test_consumed"])
        probes = report["probes"]
        self.assertEqual(probes["never_seen_category"]["status"], STATUS_ABSTAIN)
        self.assertEqual(probes["stack_extrapolation"]["status"], STATUS_ABSTAIN)
        self.assertEqual(probes["sizing_extrapolation"]["status"], STATUS_ABSTAIN)
        self.assertNotEqual(
            probes["exact_context_absent_in_domain"]["status"], STATUS_ABSTAIN
        )
        self.assertFalse(probes["exact_context_absent_in_domain"]["abstain"])

    def test_report_is_written_byte_reproducibly(self) -> None:
        report = self.report or model.build_ood_calibration_report(
            self.sample,
            folds=2,
            max_rows=800,
            tuning_max_rows=200,
            architectures=FAST_ARCHITECTURES,
        )
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "OOD_CALIBRATION_REPORT.json"
            first = model.write_ood_calibration_report(report, path)
            second = model.write_ood_calibration_report(report, path)
            self.assertEqual(first["sha256"], second["sha256"])
            self.assertEqual(first["schema"], model.OOD_REPORT_SCHEMA)
            self.assertEqual(
                first["calibration_canonical_payload_sha256"],
                report["calibration"]["canonical_payload_sha256"],
            )
            self.assertEqual(model.load_ood_calibration(path)["schema"], model.OOD_CALIBRATION_SCHEMA)

    def test_persisted_report_matches_this_module(self) -> None:
        if not REPORT_PATH.exists():
            self.skipTest("the OOD calibration report has not been generated in this worktree")
        report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
        self.assertEqual(report["schema"], model.OOD_REPORT_SCHEMA)
        self.assertEqual(
            report["provenance"]["module_sha256"], model.sha256_bytes(MODULE_PATH.read_bytes())
        )
        self.assertEqual(report["statuses"], list(model.OOD_STATUSES))
        self.assertEqual(report["scope"]["consumed_splits"], ["TRAIN"])
        self.assertFalse(report["scope"]["validation_consumed"])
        self.assertFalse(report["scope"]["test_consumed"])
        self.assertEqual(model.validate_ood_calibration(report["calibration"]), [])
        for key, value in report["acceptance_checks"].items():
            self.assertTrue(value, key)
        self.assertEqual(report["out_of_fold"]["exact_context_absent_in_domain"]["abstained_without_extrapolation"], 0)
        self.assertEqual(
            report["calibration"]["provenance"]["module_sha256"],
            model.sha256_bytes(MODULE_PATH.read_bytes()),
        )

    def test_cli_writes_the_calibration_report(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            target = Path(directory) / "OOD.json"
            buffer = io.StringIO()
            with contextlib.redirect_stdout(buffer):
                code = model.main(
                    [
                        "--ood-calibration-report",
                        "--dataset",
                        str(DATASET_PATH),
                        "--ood-report-out",
                        str(target),
                        "--ood-folds",
                        "2",
                        "--ood-max-rows",
                        "1200",
                        "--ood-tuning-rows",
                        "200",
                    ]
                )
            self.assertEqual(code, 0)
            self.assertTrue(target.exists())
            payload = json.loads(buffer.getvalue())
            self.assertEqual(payload["persisted"]["schema"], model.OOD_REPORT_SCHEMA)
            written = json.loads(target.read_text(encoding="utf-8"))
            self.assertEqual(written["scope"]["consumed_splits"], ["TRAIN"])
            self.assertFalse(written["scope"]["validation_consumed"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
