#!/usr/bin/env python3
"""#421 guard: conditional raise/JAM sizing model (legal window, no nearest price).

Covers every acceptance criterion of the sizing task:

* produced sizings are always legal -- never below the minimum raise, never
  above the engine ``max_raise_to_bb`` / effective stack;
* a missing statistic is never filled in with the nearest observed price: the
  request fails closed instead;
* every sizing request exposes its support and its uncertainty;
* the seven frozen #388/#419 raise-sizing frontiers are classified explicitly,
  and the exact-tree verdict stays independent;
* the report carries a probabilistic metric (NLL in bits, CRPS in bb) and the
  quantile calibration, plus the illegal-generation rate.

The full-dataset report is regenerated by
``python3 tools/preflop/generalized_response_model.py --sizing-report``; the
guard suite works on a deterministic stride sample so it stays fast.
"""
from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.preflop import generalized_response_model as model  # noqa: E402

MODULE_PATH = ROOT / "tools/preflop/generalized_response_model.py"
REPORT_PATH = ROOT / "analysis/issue421_generalized_response/RAISE_SIZING_MODEL_REPORT.json"
DATASET_PATH = ROOT / "analysis/issue421_generalized_response/dataset/GENERALIZED_RESPONSE_DATASET.jsonl"

FAST_CONFIG = model.make_config(tuning_max_rows=400, holdout_modulus=5)
STRIDE = 8
STEPS = 32


def _dataset_rows() -> list[dict]:
    return model.read_dataset_rows(DATASET_PATH, splits=("TRAIN", "VALIDATION"))


def _aggressive_rows(rows: list[dict]) -> list[dict]:
    return [row for row in rows if row["action"] in model.AGGRESSIVE_ACTIONS]


def _sizing_channel() -> dict:
    return model.fit_sizing_channel(_dataset_rows(), config=FAST_CONFIG)


def _free_context(**overrides) -> dict:
    """A public context whose pre-action contribution is the posted blind."""
    context = {
        "family": "UNOPENED",
        "actor_position": "LJ",
        "table_size": 6,
        "live_positions": ["LJ", "HJ", "CO", "BTN", "SB", "BB"],
        "raise_level": 0,
        "to_call_bb": 1.0,
        "pot_before_bb": 1.5,
        "effective_stack_bb": 100.0,
    }
    context.update(overrides)
    return context


class SizingWindowTests(unittest.TestCase):
    def test_explicit_engine_interval_is_authoritative(self) -> None:
        window = model.raise_sizing_window(
            _free_context(min_raise_to_bb=9.0, max_raise_to_bb=100.0), action="RAISE"
        )
        self.assertEqual(window["floor_bb"], 9.0)
        self.assertEqual(window["cap_bb"], 100.0)
        self.assertEqual(window["bounds_source"]["min"], "engine_interval")
        self.assertFalse(window["min_raise_floor_is_conservative"])
        self.assertFalse(window["fail_closed"])

    def test_derived_free_window_is_a_conservative_legal_floor(self) -> None:
        window = model.raise_sizing_window(_free_context(), action="RAISE")
        # current_bet = to_call + blind(LJ) = 1.0; prev >= BB => floor >= 2.0
        self.assertEqual(window["current_bet_bb"], 1.0)
        self.assertEqual(window["floor_bb"], 2.0)
        self.assertEqual(window["cap_bb"], 100.0)
        self.assertEqual(window["bounds_source"]["min"], "derived_conservative_floor")
        self.assertTrue(window["min_raise_floor_is_conservative"])
        self.assertFalse(window["fail_closed"])

    def test_missing_commitment_outside_the_free_regime_fails_closed(self) -> None:
        context = _free_context(raise_level=2)
        window = model.raise_sizing_window(context, action="RAISE")
        self.assertTrue(window["fail_closed"])
        self.assertEqual(window["fail_closed_reason"], "MISSING_MIN_RAISE_TO_UNVERIFIED_COMMITMENT")
        # A supplied commitment removes the ambiguity and the window is legal again.
        explicit = model.raise_sizing_window(
            context, action="RAISE", actor_commitment_bb=3.0
        )
        self.assertFalse(explicit["fail_closed"])
        # current_bet = 1.0 + 3.0 = 4.0 and prev >= max(3.0, BB) => floor = 5.0
        self.assertEqual(explicit["current_bet_bb"], 4.0)
        self.assertEqual(explicit["floor_bb"], 5.0)

    def test_missing_cap_fails_closed(self) -> None:
        context = _free_context()
        context.pop("effective_stack_bb")
        window = model.raise_sizing_window(context, action="RAISE")
        self.assertTrue(window["fail_closed"])
        self.assertEqual(window["fail_closed_reason"], "MISSING_MAX_RAISE_TO")

    def test_raise_window_empty_below_stack_fails_closed_but_jam_stays_legal(self) -> None:
        context = _free_context(raise_level=1, actor_contribution_bb=5.0, to_call_bb=30.0,
                                pot_before_bb=60.0, effective_stack_bb=40.0)
        raise_window = model.raise_sizing_window(context, action="RAISE")
        self.assertTrue(raise_window["fail_closed"])
        self.assertEqual(raise_window["fail_closed_reason"], "RAISE_WINDOW_EMPTY_BELOW_STACK")
        jam_window = model.raise_sizing_window(context, action="JAM")
        self.assertFalse(jam_window["fail_closed"])
        # The minimum raise exceeds the effective stack, so the only legal
        # aggressive target is the full shove itself.
        self.assertEqual(jam_window["floor_bb"], jam_window["cap_bb"])
        self.assertEqual(jam_window["cap_bb"], 40.0)

    def test_frontier_reconstruction_matches_the_frozen_engine_interval(self) -> None:
        frontiers = model.load_raise_sizing_frontiers()
        self.assertTrue(frontiers["loaded"])
        self.assertEqual(frontiers["frontiers_total"], 7)
        self.assertEqual(len(frontiers["frontiers"]), 7)
        for frontier in frontiers["frontiers"]:
            context = model.reconstruct_frontier_context(frontier)
            window = model.raise_sizing_window(context, action="RAISE")
            frozen = frontier["legal_target_interval_bb"]
            self.assertEqual(window["floor_bb"], frozen[0], frontier["node_id"])
            self.assertEqual(window["cap_bb"], frozen[1], frontier["node_id"])
            self.assertLessEqual(window["floor_bb"], window["cap_bb"])
            # The frozen interval is authoritative when the caller supplies it.
            explicit = model.raise_sizing_window(
                dict(context, legal_target_interval_bb=frozen), action="RAISE"
            )
            self.assertEqual(explicit["bounds_source"]["min"], "engine_interval")
            self.assertEqual(explicit["floor_bb"], frozen[0])


class SizingLegalityTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.channel = _sizing_channel()
        cls.rows = _aggressive_rows(_dataset_rows())[::STRIDE]

    def test_generated_sizings_are_always_legal(self) -> None:
        checked = 0
        for row in self.rows:
            commitment = model.recover_actor_commitment(row)
            generation = model.generate_raise_sizings(
                self.channel,
                row,
                action=row["action"],
                config=FAST_CONFIG,
                steps=STEPS,
                actor_commitment_bb=commitment,
            )
            if generation["status"] != "RESOLVED":
                self.assertEqual(generation["sizings_bb"], [])
                self.assertEqual(generation["illegal_count"], 0)
                continue
            window = generation["legal_window"]
            floor, cap = window["floor_bb"], window["cap_bb"]
            self.assertGreaterEqual(cap, floor)
            self.assertTrue(generation["sizings_bb"], row)
            minimum = window["min_raise_to_bb"]
            short_stack = minimum is not None and minimum > cap + 1e-9
            if short_stack:
                # The minimum raise exceeds the effective stack: the only legal
                # aggressive target is the full shove itself.
                self.assertEqual(floor, cap)
            for sizing in generation["sizings_bb"]:
                self.assertGreaterEqual(sizing, floor - 1e-9, (row["family"], sizing, floor))
                self.assertLessEqual(sizing, cap + 1e-9, (row["family"], sizing, cap))
                if short_stack:
                    self.assertEqual(sizing, cap)
                else:
                    self.assertGreaterEqual(sizing, minimum - 1e-9)
            self.assertEqual(generation["illegal_count"], 0)
            checked += 1
        self.assertGreater(checked, 50)

    def test_generation_is_inside_the_explicit_engine_window(self) -> None:
        context = dict(self.rows[0], min_raise_to_bb=7.0, max_raise_to_bb=25.0)
        generation = model.generate_raise_sizings(
            self.channel, context, action="RAISE", config=FAST_CONFIG, steps=STEPS
        )
        self.assertEqual(generation["status"], "RESOLVED")
        for sizing in generation["sizings_bb"]:
            self.assertGreaterEqual(sizing, 7.0 - 1e-9)
            self.assertLessEqual(sizing, 25.0 + 1e-9)

    def test_fail_closed_request_never_produces_a_target(self) -> None:
        context = _free_context(raise_level=2)
        query = model.raise_sizing_query(
            self.channel, context, action="RAISE", config=FAST_CONFIG, steps=STEPS
        )
        self.assertEqual(query["status"], "FAIL_CLOSED")
        self.assertEqual(query["generated_sizings_bb"], [])
        self.assertIsNone(query["uncertainty"])
        self.assertEqual(query["illegal_count"], 0)


class NoNearestPriceTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.channel = _sizing_channel()
        cls.rows = _aggressive_rows(_dataset_rows())[::STRIDE]

    def test_distinct_targets_are_recomputed_not_looked_up(self) -> None:
        context = _free_context(min_raise_to_bb=2.0, max_raise_to_bb=60.0, pot_before_bb=6.0, to_call_bb=2.0)
        left = model.raise_sizing_distribution(
            self.channel, context, action="RAISE", config=FAST_CONFIG, steps=64
        )
        right = model.raise_sizing_distribution(
            self.channel, dict(context, pot_before_bb=30.0), action="RAISE", config=FAST_CONFIG, steps=64
        )
        self.assertEqual(left["status"], "RESOLVED")
        self.assertEqual(right["status"], "RESOLVED")
        self.assertNotEqual(left["quantiles_bb"], right["quantiles_bb"])
        self.assertFalse(left["nearest_price_substituted"])
        self.assertFalse(left["nearest_context_substituted"])

    def test_unseen_family_falls_back_to_the_global_density_and_says_so(self) -> None:
        context = _free_context(family="NEVER_OBSERVED_FAMILY")
        query = model.raise_sizing_query(
            self.channel, context, action="RAISE", config=FAST_CONFIG, steps=STEPS
        )
        self.assertEqual(query["support"]["support_level"], "GLOBAL_FALLBACK")
        self.assertEqual(query["support"]["family_observations"], 0)
        self.assertGreater(query["support"]["global_observations"], 0)
        self.assertFalse(query["nearest_context_substituted"])

    def test_empty_channel_fails_closed_instead_of_substituting(self) -> None:
        empty = {
            "axis_knots": list(model.SIZING_AXIS),
            "actions": list(model.AGGRESSIVE_ACTIONS),
            "global": {
                action: {"total": 0, "density": [0.0] * len(model.SIZING_AXIS)}
                for action in model.AGGRESSIVE_ACTIONS
            },
            "families": {},
        }
        query = model.raise_sizing_query(
            empty, _free_context(), action="RAISE", config=FAST_CONFIG, steps=STEPS
        )
        self.assertEqual(query["status"], "FAIL_CLOSED")
        self.assertEqual(query["fail_closed_reason"], "NO_SUPPORT_INSIDE_LEGAL_WINDOW")
        self.assertEqual(query["support"]["support_level"], "NO_SUPPORT")
        self.assertEqual(query["generated_sizings_bb"], [])

    def test_observed_row_reports_zero_substitutions(self) -> None:
        for row in self.rows[:20]:
            query = model.raise_sizing_query(
                self.channel,
                row,
                action=row["action"],
                config=FAST_CONFIG,
                steps=STEPS,
                actor_commitment_bb=model.recover_actor_commitment(row),
            )
            self.assertFalse(query["nearest_price_substituted"])
            self.assertFalse(query["nearest_context_substituted"])


class SupportUncertaintyTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.channel = _sizing_channel()

    def test_every_request_exposes_support_and_uncertainty(self) -> None:
        query = model.raise_sizing_query(
            self.channel,
            _free_context(),
            action="RAISE",
            config=FAST_CONFIG,
            steps=STEPS,
        )
        self.assertEqual(query["status"], "RESOLVED")
        support = query["support"]
        for key in (
            "support_level",
            "action_observations",
            "family_observations",
            "global_observations",
            "effective_sample_size",
            "distinct_density_bins",
        ):
            self.assertIn(key, support, key)
        self.assertGreater(support["action_observations"], 0)
        uncertainty = query["uncertainty"]
        for key in (
            "entropy_nats",
            "entropy_normalized",
            "credible_interval_bb",
            "credible_interval_width_bb",
            "mode_bb",
            "median_bb",
            "mean_bb",
            "boundary_probabilities",
        ):
            self.assertIn(key, uncertainty, key)
        self.assertGreater(uncertainty["entropy_nats"], 0.0)
        self.assertGreater(uncertainty["credible_interval_width_bb"], 0.0)
        atoms = uncertainty["boundary_probabilities"]
        self.assertGreaterEqual(atoms["floor"], 0.0)
        self.assertGreaterEqual(atoms["cap"], 0.0)
        self.assertLessEqual(atoms["floor"] + atoms["cap"], 1.0 + 1e-9)
        self.assertAlmostEqual(
            atoms["floor"] + atoms["cap"] + atoms["continuous"], 1.0, places=6
        )
        # The quantile ladder is exposed and monotone.
        ladder = [query["quantiles_bb"][f"{level:.2f}"] for level in model.SIZING_QUANTILE_LEVELS]
        self.assertEqual(ladder, sorted(ladder))


class ScoringTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.channel = _sizing_channel()
        cls.rows = _aggressive_rows(_dataset_rows())[::STRIDE]

    def test_inside_window_is_scored_outside_window_is_flagged(self) -> None:
        context = dict(self.rows[0], min_raise_to_bb=5.0, max_raise_to_bb=20.0)
        inside = model.score_raise_sizing(
            self.channel, context, 8.0, action="RAISE", config=FAST_CONFIG, steps=STEPS
        )
        self.assertTrue(inside["scored"])
        self.assertTrue(inside["inside_window"])
        self.assertGreater(inside["negative_log_likelihood_bits"], 0.0)
        self.assertGreater(inside["crps_bb"], 0.0)
        self.assertGreaterEqual(inside["pit"], 0.0)
        self.assertLessEqual(inside["pit"], 1.0)

        below = model.score_raise_sizing(
            self.channel, context, 1.0, action="RAISE", config=FAST_CONFIG, steps=STEPS
        )
        self.assertFalse(below["scored"])
        self.assertEqual(below["fail_closed_reason"], "TARGET_OUTSIDE_LEGAL_WINDOW")
        above = model.score_raise_sizing(
            self.channel, context, 90.0, action="RAISE", config=FAST_CONFIG, steps=STEPS
        )
        self.assertFalse(above["scored"])
        self.assertFalse(above["nearest_price_substituted"])

    def test_boundary_atom_is_worth_more_than_the_continuous_middle(self) -> None:
        context = dict(self.rows[0], min_raise_to_bb=4.0, max_raise_to_bb=40.0)
        distribution = model.raise_sizing_distribution(
            self.channel, context, action="RAISE", config=FAST_CONFIG, steps=64
        )
        atom = distribution["density"]["atom_floor_probability"]
        if atom <= 0.0:
            self.skipTest("no minimum-raise atom in this channel")
        at_minimum = model.score_raise_sizing(
            self.channel, context, 4.0, action="RAISE", config=FAST_CONFIG, steps=64
        )
        pit_at_minimum = at_minimum["pit"]
        self.assertAlmostEqual(pit_at_minimum, atom, places=6)
        self.assertTrue(at_minimum["on_boundary_atom"])

    def test_model_beats_the_uniform_window_baseline_on_real_rows(self) -> None:
        gain = []
        for row in self.rows[:120]:
            score = model.score_raise_sizing(
                self.channel,
                row,
                float(row["target_total_bb"]),
                action=row["action"],
                config=FAST_CONFIG,
                steps=STEPS,
                actor_commitment_bb=model.recover_actor_commitment(row),
            )
            if score.get("scored"):
                gain.append(score["nll_gain_vs_uniform_bits"])
        self.assertGreater(len(gain), 40)
        self.assertGreater(sum(gain) / len(gain), 0.0)

    def test_pit_is_inside_the_unit_interval(self) -> None:
        for row in self.rows[:40]:
            score = model.score_raise_sizing(
                self.channel,
                row,
                float(row["target_total_bb"]),
                action=row["action"],
                config=FAST_CONFIG,
                steps=STEPS,
                actor_commitment_bb=model.recover_actor_commitment(row),
            )
            if score.get("scored"):
                self.assertGreaterEqual(score["pit"], 0.0)
                self.assertLessEqual(score["pit"], 1.0)


class ReportTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        rows = _aggressive_rows(_dataset_rows())[::STRIDE]
        non_aggressive = [row for row in _dataset_rows() if row["action"] not in model.AGGRESSIVE_ACTIONS][::64]
        cls.sample = rows + non_aggressive
        cls.report = model.raise_sizing_report(
            cls.sample,
            config=FAST_CONFIG,
            dataset_path=DATASET_PATH,
            steps=STEPS,
        )

    def test_report_carries_metric_calibration_and_illegal_rate(self) -> None:
        report = self.report
        self.assertEqual(report["schema"], model.RAISE_SIZING_REPORT_SCHEMA)
        metrics = report["metrics"]
        self.assertGreater(metrics["scored"], 0)
        self.assertIsNotNone(metrics["nll_bits_per_sizing"])
        self.assertIsNotNone(metrics["crps_bb"])
        self.assertEqual(metrics["illegal_generated_sizings"], 0)
        self.assertEqual(metrics["illegal_generated_rate"], 0.0)
        self.assertGreater(metrics["generated_sizings"], 0)
        self.assertGreater(metrics["nll_gain_vs_uniform_bits"], 0.0)
        calibration = metrics["calibration"]
        self.assertEqual(len(calibration["pit_histogram"]), calibration["pit_bins"])
        self.assertAlmostEqual(sum(calibration["pit_histogram"]), 1.0, places=4)
        self.assertTrue(calibration["quantile_coverage"])
        for row in calibration["quantile_coverage"]:
            self.assertIsNotNone(row["empirical"], row)
            self.assertGreater(row["n"], 0)
            self.assertGreaterEqual(row["empirical"], 0.0)
            self.assertLessEqual(row["empirical"], 1.0)
        self.assertIsNotNone(calibration["quantile_max_abs_error"])

    def test_report_guarantees_and_frontiers(self) -> None:
        report = self.report
        guarantees = report["guarantees"]
        self.assertTrue(guarantees["generated_sizings_always_legal"])
        self.assertTrue(guarantees["no_nearest_price_substitution"])
        self.assertTrue(guarantees["support_exposed_per_request"])
        self.assertTrue(guarantees["uncertainty_exposed_per_request"])
        self.assertTrue(guarantees["frontiers_classified"])
        self.assertEqual(guarantees["frontiers_resolved"] + guarantees["frontiers_fail_closed"], 7)
        frontiers = report["frontiers"]
        self.assertEqual(frontiers["total"], 7)
        self.assertTrue(frontiers["no_nearest_price_substituted"])
        for item in frontiers["items"]:
            self.assertIn(item["model_status"], ("RESOLVED", "FAIL_CLOSED"))
            self.assertEqual(item["exact_tree_status"], "UNRESOLVED")
            self.assertFalse(item["exact_tree_satisfied"])
            self.assertFalse(item["nearest_price_substituted"])
            self.assertFalse(item["nearest_context_substituted"])
            self.assertEqual(item["illegal_generated"], 0)
            if item["model_status"] == "RESOLVED":
                window = item["derived_legal_window_bb"]
                self.assertTrue(item["derived_window_matches_frozen_interval"])
                self.assertTrue(item["generated_sizings_bb"])
                for sizing in item["generated_sizings_bb"]:
                    self.assertGreaterEqual(sizing, window[0] - 1e-9)
                    self.assertLessEqual(sizing, window[1] + 1e-9)
                self.assertIsNotNone(item["support"])
                self.assertIsNotNone(item["uncertainty"])
            else:
                self.assertEqual(item["generated_sizings_bb"], [])
                self.assertIsNotNone(item["model_fail_closed_reason"])

    def test_persisted_report_matches_this_module(self) -> None:
        if not REPORT_PATH.exists():
            self.skipTest("the sizing report has not been generated in this worktree")
        report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
        self.assertEqual(report["schema"], model.RAISE_SIZING_REPORT_SCHEMA)
        self.assertEqual(
            report["provenance"]["module_sha256"], model.sha256_bytes(MODULE_PATH.read_bytes())
        )
        self.assertEqual(report["frontiers"]["total"], 7)
        self.assertTrue(report["guarantees"]["generated_sizings_always_legal"])
        self.assertEqual(report["metrics"]["illegal_generated_sizings"], 0)
        self.assertEqual(report["metrics"]["illegal_generated_rate"], 0.0)
        self.assertGreater(report["metrics"]["generated_sizings"], 0)
        self.assertGreater(report["metrics"]["scored"], 0)
        self.assertIsNotNone(report["metrics"]["nll_bits_per_sizing"])
        self.assertIsNotNone(report["metrics"]["crps_bb"])
        self.assertEqual(report["metrics"]["calibration"]["pit_bins"], 10)


if __name__ == "__main__":
    unittest.main()
